filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "changeme"
  ssl.verification_mode: "none"
  setup.template.name: "wazuh"
  setup.template.pattern: "wazuh-*"
  setup.template.enabled: false

setup.kibana:
  host: "http://kibana:5601"
  username: "elastic"
  password: "changeme"
  ssl.verification_mode: "none"

filebeat.modules:
  - module: wazuh
    alerts:
      enabled: true
    archives:
      enabled: true

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

